import { useCallback } from "react";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";

const A4_WIDTH = 210;
const A4_HEIGHT = 297;
const MARGIN = 20;
const CONTENT_WIDTH = A4_WIDTH - 2 * MARGIN;

export default function ExportModal({ isOpen, onClose, room, layout, appliedTiles, surfaces, viewerRef }) {
  const captureCanvasRoom = useCallback(async () => {
    const canvas = viewerRef.current?.querySelector("canvas");
    if (!canvas) return null;
    return canvas.toDataURL("image/png", 1.0);
  }, [viewerRef]);

  const captureCssRoom = useCallback(async () => {
    const container = viewerRef.current?.querySelector(".photo-viewer-container");
    if (!container) return null;

    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: "#ffffff",
    });
    return canvas.toDataURL("image/png", 1.0);
  }, [viewerRef]);

  const getRoomName = () => {
    return room?.name || layout?.name || "Room";
  };

  const getTileSpecs = () => {
    const specs = [];
    for (const [surface, tile] of Object.entries(appliedTiles || {})) {
      if (tile) {
        specs.push({
          surface,
          name: tile.name,
          material: tile.material,
          finish: tile.finish,
          size: tile.size,
          pattern: tile.pattern,
          grout: tile.grout,
          price: tile.price,
        });
      }
    }
    return specs;
  };

  const generatePdf = useCallback(async () => {
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    let y = MARGIN;

    pdf.setFontSize(24);
    pdf.setTextColor(30, 41, 59);
    pdf.text("Tile Visualizer — Presentation Board", MARGIN, y);
    y += 10;

    pdf.setFontSize(14);
    pdf.setTextColor(71, 85, 105);
    pdf.text(`${getRoomName()} — ${new Date().toLocaleDateString()}`, MARGIN, y);
    y += 15;

    const imgData = layout
      ? await captureCanvasRoom()
      : await captureCssRoom();

    if (imgData) {
      const imgProps = pdf.getImageProperties(imgData);
      const imgHeight = (imgProps.height * CONTENT_WIDTH) / imgProps.width;
      const maxImgHeight = A4_HEIGHT - y - MARGIN - 80;
      const finalHeight = Math.min(imgHeight, maxImgHeight);

      pdf.addImage(imgData, "PNG", MARGIN, y, CONTENT_WIDTH, finalHeight);
      y += finalHeight + 10;
    }

    const specs = getTileSpecs();
    if (specs.length > 0) {
      pdf.setFontSize(16);
      pdf.setTextColor(30, 41, 59);
      pdf.text("Applied Tiles", MARGIN, y);
      y += 10;

      for (const spec of specs) {
        if (y > A4_HEIGHT - 30) {
          pdf.addPage();
          y = MARGIN;
        }

        pdf.setFontSize(12);
        pdf.setTextColor(51, 65, 85);
        pdf.text(`${spec.surface}: ${spec.name}`, MARGIN, y);
        y += 6;

        pdf.setFontSize(10);
        pdf.setTextColor(100, 116, 139);
        const details = [
          `Material: ${spec.material}`,
          `Finish: ${spec.finish}`,
          `Size: ${spec.size}`,
          `Pattern: ${spec.pattern}`,
          `Grout: ${spec.grout}`,
          `Price: ₹${spec.price}/sq.ft`,
        ];
        for (const detail of details) {
          pdf.text(detail, MARGIN + 5, y);
          y += 5;
        }
        y += 4;
      }
    }

    pdf.setFontSize(8);
    pdf.setTextColor(148, 163, 184);
    pdf.text(
      "Generated by Tile Visualizer — Internal tool for sales team",
      A4_WIDTH / 2,
      A4_HEIGHT - 10,
      { align: "center" }
    );

    const fileName = `${getRoomName().toLowerCase().replace(/\s+/g, "-")}-presentation-${Date.now()}.pdf`;
    pdf.save(fileName);
    onClose();
  }, [captureCanvasRoom, captureCssRoom, layout, room, appliedTiles]);

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
      onClick={onClose}
      role="dialog"
      aria-modal="true"
      aria-labelledby="export-modal-title"
    >
      <div
        className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between mb-4">
          <h2 id="export-modal-title" className="text-xl font-semibold text-slate-900">
            Export Presentation
          </h2>
          <button
            onClick={onClose}
            className="rounded-lg p-1 text-slate-400 hover:text-slate-600 hover:bg-slate-100"
            aria-label="Close"
          >
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>

        <div className="space-y-3 text-sm text-slate-600">
          <p>Generate a PDF presentation board with the current room visualization and applied tile specifications.</p>

          <div className="rounded-lg bg-slate-50 p-3 space-y-2">
            <p className="font-medium text-slate-900">Room: {getRoomName()}</p>
            <p className="font-medium text-slate-900">Surfaces with tiles: {Object.keys(appliedTiles || {}).length}</p>
          </div>
        </div>

        <div className="mt-6 flex gap-3">
          <button
            onClick={onClose}
            className="flex-1 rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50"
          >
            Cancel
          </button>
          <button
            onClick={generatePdf}
            className="flex-1 rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700"
          >
            Download PDF
          </button>
        </div>
      </div>
    </div>
  );
}