import { useCallback, useState } from "react";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import { Loader2 } from "lucide-react";

const A4_WIDTH = 210;
const A4_HEIGHT = 297;
const MARGIN = 20;
const CONTENT_WIDTH = A4_WIDTH - 2 * MARGIN;

export default function ExportModal({ isOpen, onClose, room, layout, appliedTiles, surfaces, viewerRef }) {
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState(null);

  const captureCanvasRoom = useCallback(async () => {
    const canvas =
      viewerRef.current?.getCanvas?.() ||
      (viewerRef.current instanceof HTMLElement ? viewerRef.current.querySelector("canvas") : null) ||
      document.querySelector("canvas");

    if (!canvas) return null;
    try {
      return canvas.toDataURL("image/png", 1.0);
    } catch (e) {
      console.warn("Canvas export fallback:", e);
      return null;
    }
  }, [viewerRef]);

  const captureCssRoom = useCallback(async () => {
    const container =
      (viewerRef.current instanceof HTMLElement ? viewerRef.current : null) ||
      document.querySelector(".photo-viewer-container") ||
      document.querySelector("[data-room-viewer]");

    if (!container) return null;

    try {
      const canvas = await html2canvas(container, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: "#ffffff",
      });
      return canvas.toDataURL("image/png", 1.0);
    } catch (e) {
      console.warn("html2canvas export fallback:", e);
      return null;
    }
  }, [viewerRef]);

  const getRoomName = () => {
    return room?.name || layout?.name || "Room";
  };

  const getTileSpecs = () => {
    const specs = [];
    for (const [surface, tile] of Object.entries(appliedTiles || {})) {
      if (tile) {
        specs.push({
          surface,
          name: tile.title || tile.name || "Applied Tile",
          material: tile.material || "Standard",
          finish: tile.finish || "Standard",
          size: tile.size || "Standard",
          pattern: tile.pattern || "Grid",
          grout: tile.grout || "Matching",
          price: tile.price != null ? `₹${tile.price}/sq.ft` : "—",
        });
      }
    }
    return specs;
  };

  const generatePdf = useCallback(async () => {
    setGenerating(true);
    setError(null);
    try {
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      let y = MARGIN;

      pdf.setFontSize(22);
      pdf.setTextColor(30, 41, 59);
      pdf.text("Tile Visualizer — Presentation Board", MARGIN, y);
      y += 9;

      pdf.setFontSize(13);
      pdf.setTextColor(71, 85, 105);
      pdf.text(`${getRoomName()} — ${new Date().toLocaleDateString()}`, MARGIN, y);
      y += 12;

      const imgData = (await captureCanvasRoom()) || (await captureCssRoom());

      if (imgData) {
        try {
          const imgProps = pdf.getImageProperties(imgData);
          const imgHeight = (imgProps.height * CONTENT_WIDTH) / imgProps.width;
          const maxImgHeight = A4_HEIGHT - y - MARGIN - 80;
          const finalHeight = Math.min(imgHeight, maxImgHeight);

          pdf.addImage(imgData, "PNG", MARGIN, y, CONTENT_WIDTH, finalHeight);
          y += finalHeight + 10;
        } catch (imgErr) {
          console.warn("Could not embed image into PDF:", imgErr);
        }
      }

      const specs = getTileSpecs();
      if (specs.length > 0) {
        pdf.setFontSize(15);
        pdf.setTextColor(30, 41, 59);
        pdf.text("Applied Tiles", MARGIN, y);
        y += 8;

        for (const spec of specs) {
          if (y > A4_HEIGHT - 35) {
            pdf.addPage();
            y = MARGIN;
          }

          pdf.setFontSize(11);
          pdf.setTextColor(51, 65, 85);
          pdf.text(`${spec.surface}: ${spec.name}`, MARGIN, y);
          y += 5.5;

          pdf.setFontSize(9.5);
          pdf.setTextColor(100, 116, 139);
          const details = [
            `Material: ${spec.material}`,
            `Finish: ${spec.finish}`,
            `Size: ${spec.size}`,
            `Price: ${spec.price}`,
          ];
          for (const detail of details) {
            pdf.text(detail, MARGIN + 4, y);
            y += 4.5;
          }
          y += 3;
        }
      }

      pdf.setFontSize(8);
      pdf.setTextColor(148, 163, 184);
      pdf.text(
        "Generated by Tile Visualizer — Presentation Export",
        A4_WIDTH / 2,
        A4_HEIGHT - 10,
        { align: "center" }
      );

      const fileName = `${getRoomName().toLowerCase().replace(/\s+/g, "-")}-presentation-${Date.now()}.pdf`;
      pdf.save(fileName);
      onClose();
    } catch (err) {
      console.error("PDF generation failed:", err);
      setError(err.message || "Failed to generate PDF. Please try again.");
    } finally {
      setGenerating(false);
    }
  }, [captureCanvasRoom, captureCssRoom, layout, room, appliedTiles, onClose]);

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
      onClick={onClose}
      role="dialog"
      aria-modal="true"
      aria-labelledby="export-modal-title"
    >
      <div
        className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between mb-4">
          <h2 id="export-modal-title" className="text-xl font-semibold text-slate-900">
            Export Presentation
          </h2>
          <button
            onClick={onClose}
            className="rounded-lg p-1 text-slate-400 hover:text-slate-600 hover:bg-slate-100"
            aria-label="Close"
          >
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>

        {error && (
          <div className="mb-3 rounded-lg bg-red-50 p-3 text-xs font-semibold text-red-600">
            {error}
          </div>
        )}

        <div className="space-y-3 text-sm text-slate-600">
          <p>Generate a PDF presentation board with the current room visualization and applied tile specifications.</p>

          <div className="rounded-lg bg-slate-50 p-3 space-y-2">
            <p className="font-medium text-slate-900">Room: {getRoomName()}</p>
            <p className="font-medium text-slate-900">Surfaces with tiles: {Object.keys(appliedTiles || {}).length}</p>
          </div>
        </div>

        <div className="mt-6 flex gap-3">
          <button
            onClick={onClose}
            disabled={generating}
            className="flex-1 rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50"
          >
            Cancel
          </button>
          <button
            onClick={generatePdf}
            disabled={generating}
            className="flex flex-1 items-center justify-center gap-1.5 rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 disabled:opacity-50"
          >
            {generating && <Loader2 size={15} className="animate-spin" />}
            {generating ? "Generating…" : "Download PDF"}
          </button>
        </div>
      </div>
    </div>
  );
}